[workspace]
members = [
    "rapyd",
    "rapyd-macros",
    "rapyd-playground",
    "rapyd-web-playground",
    "rapyd-fine-grained-compilation-output",
    "struct-based-template",
    "rapyd-macros-new"
]
resolver = "2"